-- FOR improving startup time
vim.loader.enable()

require("user.options")
require("user.keymaps")
require("user.plugins")
require("user.colorscheme")
require("user.comment")
require("user.cmp")
require("user.lsp")
require("user.telescope")
require("user.treesitter")
require("user.autopairs")
require("user.gitsigns")
require("user.nvimtree")
require("user.bufferline")
require("user.indent-blankline")
require("user.lualine")
require("user.dashboard")
